# Generated by Django 4.2.3 on 2023-07-31 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('bin', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('country', models.CharField(max_length=128)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.industry')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_app.company')),
            ],
        ),
    ]
